/**
  ******************************************************************************
  * File Name          : RTC.h
  * Description        : This file provides code for the configuration
  *                      of the RTC instances.
  ******************************************************************************
  *
  * This file is generated by merelda, modified from the tim.c file
  ******************************************************************************
  */
/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __rtc_H
#define __rtc_H
#ifdef __cplusplus
 extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "stm32l0xx.h"
//#include "stm32l0xx_hal.h"

	 
/* Comment to disable displaying the time on the debugger */
#define DISPLAY_ON_DUBUGGER
#define RTC_CLOCK_SOURCE_LSE
	 
#ifdef RTC_CLOCK_SOURCE_LSI
  #define RTC_ASYNCH_PREDIV    0x7F
  #define RTC_SYNCH_PREDIV     0x0130
#endif

extern RTC_HandleTypeDef hrtc;

void MX_RTC_Init(void);
void RTC_CalendarConfig(void);
void RTC_CalendarShow(uint8_t* showtime, uint8_t* showdate);
void rtc_write(time_t t);
time_t rtc_read(void);

#ifdef __cplusplus
}
#endif
#endif /*__ rtc_H */

/**
  * @}
  */

/**
  * @}
  */

/************************ (C) COPYRIGHT STMicroelectronics *****END OF FILE****/
